---
galaxy_info:
  role_name: system-updates
  description: Ansible role to update the system, upgrade all packages to the latest version, and restart necessary services if required.
  author: Zifa Mathebula
  company: Marabele Africa
  license: MIT
  min_ansible_version: 2.10
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: Debian
      versions:
        - stretch
        - buster
  galaxy_tags:
    - system
    - updates
    - services