---
- name: Restart Docker Service
  systemd:
    name: docker
    state: restarted
  listen: "Restart Networking Service"

- name: Reboot Server
  reboot:
    reboot_timeout: 300
  listen: "Restart Docker Service"