---
# tasks file for creating users

- name: Create system users
  user:
    name: "{{ item.name }}"
    create_home: "yes"
    system: "yes"
    shell: /bin/bash
    state: present
  with_items: "{{ system_users }}"
  become: "yes"

- name: Add system users to groups
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
  with_items: "{{ system_users }}"
  become: "yes"

- name: Add user to the sudoers, to enable executing any command without password
  copy:
    dest: "/etc/sudoers.d/{{ item.name }}"
    content: "{{ item.name }}  ALL=(ALL)  NOPASSWD: ALL"
  with_items: "{{ system_users }}"
  become: "yes"

- name: Deploy SSH Key
  authorized_key:
    user="{{ item.name }}"
    key="{{ lookup('file', '{{ item.ssh_key_path }}') }}"
    state=present
  with_items: "{{ system_users }}"
  become: "yes"